puts "SEEDING DATA"

puts "SEEDING EXERCISES..."

Exercise.create!(name: "Press-Ups", description: "This exercise works the pectoral muscles in your chest and the triceps. These are the muscles in the back of your upper arms. You don't need any equipment to get started with press-ups.  To assist with keeping proper lower-back alignment, slim your waistline by trying to pull your belly button in and tightening your abdominal muscles.", muscle_group: "Upper Body and Core", intensity: "Beginner", form: "Hips should be in line with the shoulders, and the lower-back should have a neutral curve—not completely flat, but not overly curved either.", image: "https://images.medicinenet.com/images/article/main_image/what-are-push-ups-for.jpg", liked: true, seconds:0, reps:15, sets: 3)

Exercise.create!(name: "Squats", description: "This exercise works the glute and inner thigh muscles. As your buttocks become firm, your posture and balance might improve. You don't need any equipment to get started with squats. While squatting Pause when your thighs reach about parallel to the ground. Push through your entire foot to return to start.", muscle_group: "Buttocks, Front and Back Thigh and Groin", intensity: "Beginner", form: "Stand with your feet shoulder-width apart, toes slightly out, core braced, and chest up. Initiate a basic squat movement — hips back, knees bent, ensuring they fall out, not in.",  image: "https://i.insider.com/61ae5c2c35814a00195eaf7a?width=1136&format=jpeg", liked: false, seconds:0, reps:8, sets:5)

Exercise.create!(name: "Pull-Ups", description: "This exercise works several muscles of the upper body, including the latissimus dorsi, trapezius, and biceps brachii. A pull-up may be performed with overhand, underhand, neutral, or rotating hand position. The term chin-up is sometimes used to refer to the pull-up performed with supinated grip.", muscle_group: "Lats, Biceps, and Core", intensity: "Intermediate", form: "Grasp the bar with an overhand grip with your hands just wider than shoulder-width apart. Let your body hang straight down with your arms fully extended. Pull up and squeeze your lats until your chin is over the bar, before lowering slowly to the start position without swinging.", image: "https://image.boxrox.com/2021/05/pull-up.jpg", liked: false, seconds:0, reps:6, sets:3)

Exercise.create!(name: "Lunge", description: "This exercise works the muscles crossing the hip, knee, ankle, and helps improve balance and core stability. A lunge can be done as a bodyweight exercise, with weights, or for plyometric training (jump or reactive training) exercise.", muscle_group: "Glutes, Hamstrings, Calves", intensity: "Beginner", form: "Stand with your feet hip-width apart. Step forward and bend both knees, lowering until your knees are bent at a 90-degree angle. Shift forward onto the lead leg. Push off on both legs and step through, lifting your back leg and bringing it forward so your rear foot lands ahead of you in a lunge position.", image: "https://as1.ftcdn.net/v2/jpg/01/68/55/06/1000_F_168550673_q2i5JVo2sTRyBmqaY7OQYlURZ7vomuVS.jpg", liked: false, seconds:0, reps:15, sets:4)

Exercise.create!(name: "Dumbbell Rows", description: "Dumbbell Row is an exercise where you can get a long range of motion and really focus on the working muscles. By rowing the dumbbell closer to your hip or shoulder, you can control what muscles will work the hardest.", muscle_group: "Upper Back", intensity: "Beginner", form: "One hand on a bench and an even stance with your feet. Keep hips square to the ground the entire time; keeping your core active as you row. Pull the dumbbell up by pulling your elbow as high as you can.", image: "https://www.verywellfit.com/thmb/zKoPdnJ79lis8rZT5TAyM2gAoks=/500x350/filters:no_upscale():max_bytes(150000):strip_icc()/DominicDiSaia-56a8f3803df78cf772a22c14.jpg", liked: false, seconds:0, reps: 15, sets: 4)

Exercise.create!(name: "Plank", description: "The plank is an isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.", muscle_group: "Core", intensity: "Beginner", form: "Hands directly under shoulders (slightly wider than shoulder width). Ground toes into the floor and squeeze glutes to stabilize body. Your legs should be working, too — don't lock or hyperextend knees. Neutralize your neck and spine by looking at a spot on the floor about a foot beyond your hands. Your head should be in line with your back. Hold the position for 30 seconds.", image: "https://media.self.com/photos/615378c1150f8742ac896749/4:3/w_2560%2Cc_limit/Forearm%2520Plank%2520-%2520Delise_001.jpg", liked: false, seconds: 30, reps: 0, sets: 0)

Exercise.create!(name: "Side Planks", description: "The Side Plank is an excellent exercise for strengthening the oblique abdominal muscles, which don't get worked as much during ab exercises such as crunches.", muscle_group: "Adominal Muscles, Triceps, Hamstrings, Gluteus Maximus, Gluteus Medius, Lower-Back", intensity: "Beginner", form: "Engage abdominal muscles, drawing the navel toward your spine. Lift your hips and knees while exhaling. Ensure your torso is a straight line. Hold the position. After several breaths, inhale and return to the starting position. The goal should be to hold for 60 seconds. Change sides and repeat.", image: "https://bod-blog-assets.prod.cd.beachbodyondemand.com/bod-blog/wp-content/uploads/2022/07/29135109/Side_Plank_Hip_Lift_770.jpeg", liked: false, seconds: 60, reps: 0, sets: 0)

Exercise.create!(name: "Glute Bridge", description: "A glute bridge is an exercise that involves lying on the ground on your back and thrusting your hips upwards. It is a simple at-home exercise that can be performed with no equipment, and it can increase glute strength, core stability, and lower back health.", intensity: "Beginner", form: "Lay down on your back with your knees bent. Place your feet flat on the ground and hip-width apart with your heels about 6-8 inches away from your glutes. Place your arms by your sides with your palms facing up. Squeeze your glutes and your abs as you start to lift your hips toward the ceiling. Raise your hips as high as you can go without arching your back. The goal is to raise your hips until your body is in a straight line from your knee to your hip and to your shoulder; hold for two seconds. Slowly lower the hips down to the floor, keeping tension in the glutes and abs as you lower down.", image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/glutebridge-1603107150.jpg?resize=480:*", liked: false, seconds:0, reps: 15, sets: 4)

Exercise.create!(name: "Single-Leg Deadlifts", description: "A Single Leg Deadlift is a hip-hinge movement that strengthens the back, core and legs. This variation of a traditional deadlift involves one leg lifting off the ground and extending out behind you.", muscle_group: "Amstrings, Gluteus Maximus, Gluteus Medius, Ankles, Core", intensity: "Beginner", form: "Begin standing with your feet hip-width apart and parallel. Lift your extended leg and pitch your body forward until your body forms a “T” shape. Your arms should be hanging straight down, holding onto the weight. Keep a slight bend in your standing leg. Slowly bring in your extended leg and return to starting position. Repeat with the other leg.", image: "https://www.oxygenmag.com/wp-content/uploads/2021/01/db-single-leg-deadlift-scaled.jpg?width=730", liked: false, seconds:0, reps: 10, sets: 3)

Exercise.create!(name: "Standing Overhead Dumbbell Presses", description: "Compound exercises, which utilize multiple joints and muscles, are perfect for busy bees as they work several parts of your body at once. A standing overhead press isn't only one of the best exercises you can do for your shoulders, but it also engages your upper back and core.", muscle_group: "Triceps, Shoulders, Glutes, Traps, and Lower-Back Muscles", intensity: "Beginner", form: "Stand upright and keep the back straight. Hold a dumbbell in each hand, at the shoulders, with an overhand grip.", image: "https://64.media.tumblr.com/3891ef3296194c49c0d9851df2221e2a/tumblr_orzvks9GSa1t5lpm4o1_1280.jpg", liked: false, seconds:0, reps: 12, sets: 3)

puts "EXERCISES SEEDED"

puts "SEEDING QUOTES..."

Quote.create!(text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson")


Quote.create!(text: "Once you learn to quit, it becomes a habit.", author: "Vince Lombardi Jr")

Quote.create!(text: "A year from now you may wish you had started today.", author: "Karen Lamb")

Quote.create!(text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau")

Quote.create!(text: "Our growing softness, our increasing lack of physical fitness, is a menace to our security.", author: "John F. Kennedy")

puts "QUOTES SEEDED"

puts "SEEDING DONE"